using Microsoft.Extensions.AI.VllmChatClient.Gemma;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Microsoft.Extensions.AI;

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(VllmChatRequest))]
[JsonSerializable(typeof(VllmChatRequestMessage))]
[JsonSerializable(typeof(VllmOpenAIChatRequest))]
[JsonSerializable(typeof(VllmOpenAIChatRequestMessage))]
[JsonSerializable(typeof(VllmOpenAITextContentPart))]
[JsonSerializable(typeof(VllmOpenAIImageContentPart))]
[JsonSerializable(typeof(VllmOpenAIImageUrl))]
[JsonSerializable(typeof(VllmChatResponse))]
[JsonSerializable(typeof(VllmChatResponseMessage))]
[JsonSerializable(typeof(VllmFunctionCallContent))]
[JsonSerializable(typeof(VllmFunctionResultContent))]
[JsonSerializable(typeof(VllmFunctionTool))]
[JsonSerializable(typeof(VllmFunctionToolCall))]
[JsonSerializable(typeof(VllmFunctionToolParameter))]
[JsonSerializable(typeof(VllmFunctionToolParameters))]
[JsonSerializable(typeof(VllmRequestOptions))]
[JsonSerializable(typeof(VllmOpenAIToolChoice))]
[JsonSerializable(typeof(VllmOpenAIToolChoiceFunction))]
[JsonSerializable(typeof(VllmResponseFormat))]
[JsonSerializable(typeof(VllmJsonSchemaResponseFormat))]
[JsonSerializable(typeof(VllmStructuredOutputs))]
[JsonSerializable(typeof(VllmTool))]
[JsonSerializable(typeof(VllmToolResponse))]
[JsonSerializable(typeof(VllmToolCall))]
[JsonSerializable(typeof(VllmEmbeddingRequest))]
[JsonSerializable(typeof(VllmEmbeddingResponse))]
[JsonSerializable(typeof(VllmChatStreamResponse))]
[JsonSerializable(typeof(VllmReasoningDetail))]
[JsonSerializable(typeof(VllmReasoningOptions))]
[JsonSerializable(typeof(VllmResponsesRequest))]
[JsonSerializable(typeof(VllmResponsesMessageInput))]
[JsonSerializable(typeof(VllmResponsesFunctionCallInput))]
[JsonSerializable(typeof(VllmResponsesFunctionCallOutputInput))]
[JsonSerializable(typeof(VllmResponsesImageContentPart))]
[JsonSerializable(typeof(VllmResponsesTextContentPart))]
[JsonSerializable(typeof(VllmResponsesResponse))]
[JsonSerializable(typeof(VllmResponsesOutputItem))]
[JsonSerializable(typeof(VllmResponsesContentPart))]
[JsonSerializable(typeof(VllmResponsesUsage))]
[JsonSerializable(typeof(VllmAnthropicMessagesRequest))]
[JsonSerializable(typeof(VllmAnthropicMessage))]
[JsonSerializable(typeof(VllmAnthropicTextBlock))]
[JsonSerializable(typeof(VllmAnthropicTextBlock[]))]
[JsonSerializable(typeof(VllmAnthropicThinkingBlock))]
[JsonSerializable(typeof(VllmAnthropicImageBlock))]
[JsonSerializable(typeof(VllmAnthropicImageSource))]
[JsonSerializable(typeof(VllmAnthropicToolUseBlock))]
[JsonSerializable(typeof(VllmAnthropicToolResultBlock))]
[JsonSerializable(typeof(VllmAnthropicTool))]
[JsonSerializable(typeof(VllmAnthropicToolChoice))]
[JsonSerializable(typeof(VllmAnthropicThinkingOptions))]
[JsonSerializable(typeof(VllmAnthropicMessagesResponse))]
[JsonSerializable(typeof(VllmAnthropicContentBlock))]
[JsonSerializable(typeof(VllmAnthropicUsage))]
[JsonSerializable(typeof(VllmAnthropicStreamEvent))]
[JsonSerializable(typeof(VllmAnthropicStreamDelta))]
[JsonSerializable(typeof(Dictionary<string, object?>))]
[JsonSerializable(typeof(Dictionary<string, JsonElement>))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(object))]
[JsonSerializable(typeof(object[]))]
[JsonSerializable(typeof(string[]))]
[JsonSerializable(typeof(JsonElement[]))]
[JsonSerializable(typeof(GeminiRequest))]
[JsonSerializable(typeof(GeminiResponse))]
[JsonSerializable(typeof(GeminiContent))]
[JsonSerializable(typeof(GeminiPart))]
[JsonSerializable(typeof(GeminiInlineData))]
[JsonSerializable(typeof(GeminiFunctionCall))]
[JsonSerializable(typeof(GeminiFunctionResponse))]
[JsonSerializable(typeof(GeminiGenerationConfig))]
[JsonSerializable(typeof(GeminiThinkingConfig))]
[JsonSerializable(typeof(GeminiTool))]
[JsonSerializable(typeof(GeminiFunctionDeclaration))]
[JsonSerializable(typeof(GeminiCandidate))]
[JsonSerializable(typeof(GeminiUsageMetadata))]
internal sealed partial class JsonContext : JsonSerializerContext;
